#!/bin/bash
env.BUILD_NUMBER=BASTION_123
env.TICKET_NUMBER="1234"
env.BUILD_ID="BASTION_1.2.3."
env.TARGET_HOST="10.0.0.51"
env.BUILD_DISPLAY_NAME="TARGET-HOST,USER"
env.DB_URL="hello"
env.DB_URL2="hello2"
